apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-worker
  labels:
    app: remediation-worker # Burası kalsın
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-remediation-engine # Burayı Service ile eşitledik
  template:
    metadata:
      labels:
        app: cloud-remediation-engine # Burayı Service ile eşitledik
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: worker
        image: oguzhanozmenn/remediation-worker:v1.1
        ports:
        - containerPort: 8000
          name: http # Service'teki port ismiyle (http) uyumlu olması için