apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-remediation-monitor
  namespace: monitoring
  labels:
    release: kube-stack         # Targets listendeki diğer servislerle aynı label
    prometheus: monitoring-stack # Terminal çıktındaki ikinci ihtimal
spec:
  namespaceSelector:
    any: true # Uygulaman farklı bir namespace'de olsa bile bulur
  selector:
    matchLabels:
      app: cloud-remediation-engine # service.yaml'daki label ile aynı
  endpoints:
  - port: metrics # service.yaml'daki port ismiyle aynı
    path: /metrics
    interval: 15s