apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-remediation-monitor
  namespace: monitoring
  labels:
    release: kube-stack # Prometheus'un bunu tanıması için şart!
spec:
  selector:
    matchLabels:
      app: cloud-remediation-engine
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s