apiVersion: v1
kind: Service
metadata:
  name: cloud-remediation-service
  labels:
    app: cloud-remediation-engine
spec:
  selector:
    app: cloud-remediation-engine
  ports:
    - name: metrics # ServiceMonitor buradaki isme bakar
      protocol: TCP
      port: 8000
      targetPort: 8000