apiVersion: v1
kind: Service
metadata:
  name: cloud-remediation-service
  labels:
    app: cloud-remediation-engine
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: cloud-remediation-engine
  ports:
    - name: metrics        # <--- BURAYI EKLEDİK, ÇOK ÖNEMLİ!
      protocol: TCP
      port: 8000
      targetPort: 8000